Major documentation update with minor code refractoring
ITMO-NSS-team/BAMT pull request #38
Opened 2023-02-28 19:41 UTC by jrzkaminski

1. Documentation preview is available here:
https://jrz-bamt-test.readthedocs.io/en/latest/index.html

2. Readme is fully updated and now written in reStructuredText instead of CommonMark Markdown.

3. Minor code refactoring with autopep8 and some changes to code to make it more readable and clean.

4. Added a new github action for code coverage badge, but adding a secret (API key for codecov)  is still essential. I could not do it for some reason.

2023-02-28 22:33 UTC, Anaxagor approved these changes

2023-02-28 22:36 UTC, Anaxagor requested changes
Lets rename 'BN Algorithms' section to 'BN Theory' in Documentation

2023-03-01 07:57 UTC, jrzkaminski commented
> Lets rename 'BN Algorithms' section to 'BN Theory' in Documentation

done

2023-03-01 09:20 UTC, Anaxagor submitted a review, later dismissed

2023-03-01 17:03 UTC, Roman223 commented
Thank you for your contribution @jrzkaminski!

Everything is good, except a few things:
1. It seems, that in the Learn and Visualize Bayesian Network section missed the part about setting models (regressors and classifiers). See the following imports: 
```
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
```
2. User is also capable of changing a directory, where models stores with `sample(models_dir = dir)`. I think we should add this in tutorials.
3. I think we should add section about data management in BAMT. 
- First we need to declare, which data types user should use. We have been reported that sometimes types of columns are uncertain (ex. `pd.Object`), and BAMT will not be able to work with them. For example, column type is `Object` (so it is a disc) but in fact it must be a disc_num.
See from `GraphUtils.py`:
```
disc = ['str', 'O', 'b', 'categorical', 'object', 'bool']
disc_numerical = ['int32', 'int64']
cont = ['float32', 'float64']
```
PS: I think we will allocate it into config.
- Then we should explain, how we store models. To do this, I think, it will be better to describe config's params and serialization methods and rules.
4. Typos.
5. User also can pass argument `as_df: bool` to some functions (`get_info`, `sample`). It is usefull for PyCharm.

2023-03-01 19:24 UTC, Roman223 approved these changes

2023-03-01 20:25 UTC, Anaxagor approved these changes

2023-03-01 20:25 UTC, merged